import { Reveal } from './Reveal';
type Item={name:string;description?:string;price:string};
const sections:{title:string;items:Item[]}[]=[
{title:'ראשונות',items:[{name:'טרטר טונה אדומה',description:'טונה אדומה, שמן זית, לימון, צ׳ילי, עשבי תיבול',price:'72 ₪'},{name:'קרפצ׳יו דג ים',description:'צלפים, לימון, שמן זית, מלח ים',price:'68 ₪'},{name:'קלמרי על הגריל',description:'שום, לימון, פטרוזיליה ושמן זית',price:'74 ₪'},{name:'סביצ׳ה לבן',description:'דג ים טרי, הדרים, בצל סגול, צ׳ילי, כוסברה',price:'68 ₪'},{name:'סלט NOIR',description:'עגבניות, מלפפון, פטה, זיתים, בצל סגול',price:'46 ₪'}]},
{title:'מהים',items:[{name:'דג ים שלם',description:'לימון חרוך, עשבי תיבול, שמן זית',price:'128 ₪'},{name:'לברק צלוי',description:'ירקות ים תיכוניים, לימון, אורגנו',price:'138 ₪'},{name:'דניס חינני',description:'שום קונפי, לימון, עשבי תיבול',price:'128 ₪'},{name:'פסטת פירות ים',description:'שרימפס, קלמרי, מולים, עגבניות ושום',price:'126 ₪'},{name:'שרימפס צרובים',description:'חמאת שום, לימון, צ׳ילי, עשבי תיבול',price:'118 ₪'},{name:'פילה מוסר',description:'קרם לימון, ירקות צלויים, שמן זית',price:'136 ₪'}]},
{title:'תוספות',items:[{name:'תפוחי אדמה יווניים',description:'לימון, אורגנו, שמן זית',price:'32 ₪'},{name:'ירקות ים תיכוניים',description:'קישוא, פלפל, בצל, עשבי תיבול',price:'34 ₪'},{name:'סלט עגבניות שרי',description:'בצל סגול, בזיליקום, שמן זית',price:'36 ₪'},{name:'לחם מחמצת',description:'שמן זית, מלח ים',price:'22 ₪'}]},
{title:'קינוחים',items:[{name:'בקלאווה פיסטוק',description:'פיסטוק, דבש, גלידת וניל',price:'48 ₪'},{name:'פנקוטה לימון',description:'קרם לימון, פירות עונתיים',price:'44 ₪'},{name:'טארט שקדים',description:'שקדים קלויים, גלידת וניל',price:'46 ₪'},{name:'סורבה הדרים',description:'סורבה לימון, תפוז ואשכולית',price:'36 ₪'}]},
{title:'שתייה',items:[{name:'קפה יווני',price:'18 ₪'},{name:'אספרסו',price:'14 ₪'},{name:'מים מינרליים',price:'16 ₪'},{name:'סודה עם לימון ונענע',price:'18 ₪'},{name:'לימונדה ביתית',price:'24 ₪'}]}];
export function Menu(){return <section id="menu" className="section bg-foam"><Reveal className="mx-auto mb-16 max-w-xl text-center"><p className="eyebrow mb-5 text-ocean">The kitchen</p><h2 className="display text-6xl leading-none sm:text-7xl">OUR MENU</h2><p dir="rtl" className="mt-5 text-sm text-ink/65">דגים טריים, חומרי גלם מקומיים וטעמים של ים תיכון.</p></Reveal><div dir="rtl" className="mx-auto grid max-w-5xl gap-x-16 gap-y-14 md:grid-cols-2">{sections.map((section,i)=><Reveal delay={i*.04} key={section.title}><h3 className="display border-b border-ink/30 pb-3 text-right text-4xl">{section.title}</h3><div className="mt-2">{section.items.map(item=><div className="border-b border-ink/10 py-4" key={item.name}><div className="flex justify-between gap-4"><h4 className="text-sm font-bold">{item.name}</h4><span className="text-xs font-bold whitespace-nowrap">{item.price}</span></div>{item.description&&<p className="mt-1 text-xs leading-5 text-ink/60">{item.description}</p>}</div>)}</div></Reveal>)}</div></section>}
